name: Red Hat JBoss Data Grid
abbreviated_name: JBoss Data Grid
current_version: 7.0.0.GA
description: 'An intelligent, distributed caching solution that boosts application performance, provides greater deployment flexibility, and minimizes the overhead of standing up new applications.'
upstream_projects:
  - infinispan
  - jgroups
  - hibernate_subprojects_search
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datagrid.png
    url: /quickstarts/datagrid/helloworld-jdg
    text: Get started with Data Grid with this basic Infinispan example

