name: Red Hat JBoss BRMS
abbreviated_name: JBoss BRMS
product_logo: brms.png
current_version: 6.2.0.GA
documentation_minor_version: 6.2
description: 'Quickly create and change business rules with this business rules management system.'
upstream_projects:
  - optaplanner
  - drools
  - guvnor
#  - uberfire
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_brms.png
    url: /quickstarts/brms/helloworld-brms
